
// Giving an unordered sequence generated by A~H, we want to judge whether the sequence 
//   is a FILO(first in last out)  sequence.


#include<stdio.h>

int main(){
	int count=0,top=0; 
	char x='A',s,Q[8];
	scanf("%c", &s);
	while(count<8){
	if(top>0 && Q[top-1]==s){
		top--;
		scanf("%c", &s);
		count++;
		}
	else if(x<='H') {
		Q[top++]=x++;
	}
	else {
		printf("0");return 0;}
	}
	printf("1"); return 0; 
 } 
